# Generated by Django 5.2.10 on 2026-02-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos_gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='monto',
            field=models.FloatField(),
        ),
    ]
