# Generated by Django 5.2.10 on 2026-03-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos_gastos', '0002_alter_movimientos_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
